
export const siteMetadata = {
    title: 'SVGPix',
    author: 'Nidhinkumar',
    headerTitle: 'SVGPix',
    description: 'Unleash the AI magic! Turn your text into dazzling SVG art for free. No sweat, just pure tech wizardry!Unleash the AI magic! Turn your text into dazzling SVG art for free. No sweat, just pure tech wizardry!',
    language: 'en-us',
    theme: 'light',
    siteUrl: 'https://svgpix.vercel.app/',
    siteLogo: '/logo.png',
    socialBanner: '/social-banner.png',
    email: 'nidhin6392ai@gmail.com', 
    github: 'https://github.com/nidhinkumar06',
    twitter: 'https://twitter.com',
    facebook: 'https://facebook.com',
    youtube: 'https://www.youtube.com',
    linkedin: 'https://www.linkedin.com/nidhinkumar06',
    dribbble: 'https://www.dribbble.com',
    locale: 'en-US',
  }